# Generated by Django 5.0.3 on 2024-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='amount'),
        ),
    ]
