# Generated by Django 5.0.3 on 2024-05-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_expense_expense_group_alter_expense_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_group',
        ),
        migrations.DeleteModel(
            name='ExpenseGroup',
        ),
    ]
